import Head from "next/head";
import styles from "../styles/Home.module.css";
import useNews from "../utils/utils";
import { Skeleton } from "@mui/material";

export default function NewzHome() {
  function dateFormat() {
    const currentDate = new Date();
    let day = currentDate.getDate();
    let month = currentDate.getMonth() + 1;
    let year = currentDate.getFullYear();
    // format = 2022-03-13
    let formattedDate = year + "-" + month + "-" + day;
    return formattedDate;
  }

  const params = {
    mainChoice: "top-headlines",
    secondaryChoice: "sports",
    date: dateFormat(),
  };
  const { news, isLoading, isError } = useNews(params);

  if (isLoading)
    return (
      <div className={styles.container}>
        <main className="App">
          <h1>NewzWorthy</h1>
          <Skeleton variant="text" />
        </main>
      </div>
    );
  if (isError) return <h1>Something went wrong!</h1>;

  return (
    <div className={styles.container}>
      <Head>
        <title>NewzWorthy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="App">
        <h1>NewzWorthy</h1>
        <div>
          {news.data.articles.map((item, index) => (
            <div key={index}>
              <h2>{item.title}</h2>
              <img src={item.urlToImage} />
              <h5>{item.description}</h5>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
