import Head from "next/head";
import styles from "../styles/Home.module.css";
import useSWR from "swr";
import NewsPage from "./newspage";
import useNews from "../utils/utils";
import { Skeleton } from "@mui/material";
// const fetcher = (url) => fetch(url).then((res) => res.json());

export default function Home() {
  //const { data: result, error } = useSWR("api/news", fetcher);
  // if (error) return <h1>Something went wrong!</h1>;
  // if (!result) return <h1>Loading...</h1>;

  const { news, isLoading, isError } = useNews("top-headlines");

  if (isLoading)
    return (
      <>
        <Skeleton variant="text" />
        <Skeleton variant="text" />
        <Skeleton variant="text" />
        <Skeleton variant="text" />
        <Skeleton variant="text" />
        <Skeleton variant="text" />
        <Skeleton variant="text" />
        <Skeleton variant="text" />
        <Skeleton variant="text" />
        <Skeleton variant="text" />
        <Skeleton variant="text" />
        <Skeleton variant="text" />
      </>
    );
  if (isError) return <h1>Something went wrong!</h1>;

  console.log("articles: ", news.data.articles);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="App">
        <h1>NewzWorthy</h1>
        <div>
          {news.data.articles.map((item, index) => (
            <NewsPage
              key={index}
              title={item.title}
              article={item.description}
            ></NewsPage>
          ))}
        </div>
      </main>
    </div>
  );
}
