import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Skeleton } from "@mui/material";
import React from "react";

const StaticPropsNewz = ({ articles }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NewzWorthy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="App">
        <h1>NewzWorthy</h1>
        <div>
          {articles.map((item, index) => (
            <div key={index}>
              <h2>{item.title}</h2>
              <img src={item.urlToImage} />
              <h5>{item.description}</h5>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  function dateFormat() {
    const currentDate = new Date();
    let day = currentDate.getDate();
    let month = currentDate.getMonth() + 1;
    let year = currentDate.getFullYear();
    // format = 2022-03-13
    let formattedDate = year + "-" + month + "-" + day;
    return formattedDate;
  }

  const res = await fetch(
    `https://newsapi.org/v2/top-headlines?language=en&from=${dateFormat()}&apiKey=${
      process.env.NEWS_KEY
    }`
  );
  const articles = await res.json();
  return {
    props: {
      articles: articles.articles,
    },
    revalidate: 60, //revalidation period
  };
};

export default StaticPropsNewz;
