import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import React from "react";

const StaticPathsNewz = ({ article }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NewzWorthy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="App">
        <h1>NewzWorthy</h1>
        <div>This is article {article.id}</div>
        <div>{article.title}</div>
      </main>
    </div>
  );
};

export const getStaticProps = async (context) => {
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/posts/${context.params.id}`
  );
  const article = await res.json();
  return {
    props: {
      article,
    },
  };
};

// This happens on every request
export const getStaticPaths = async () => {
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/posts`
    // `https://newsapi.org/v2/top-headlines?language=en&from=${dateFormat()}&apiKey=${
    //   process.env.NEWS_KEY
    // }`
  );
  const articles = await res.json();

  //const ids = articles.map((article) => {});

  const paths = articles.map((article) => ({
    params: { id: article.id.toString() },
  }));

  return {
    paths,
    fallback: false,
  };
};

export default StaticPathsNewz;
